//! Lightweight Advanced SubStation Alpha (`*.ass` / `*.ssa`)
//! import + export.
//!
//! Scope of this module (spec: "keep it lightweight"):
//! * import: parse `[Events]` `Dialogue:` lines for start/end/text
//!   (inline override groups `{...}` stripped, `\N` and `\n` treated
//!   as line breaks). Style / margin / font info is NOT preserved on
//!   round-trip — that would drag half of libass into our tree.
//! * export: emit a stable, minimal `[Script Info]` +
//!   `[V4+ Styles]` + `[Events]` file using a single default style.
//!   Speakers are written into the `Name` column when present.

use super::models::SubtitleSegment;

const DEFAULT_STYLE_NAME: &str = "Default";
const DEFAULT_STYLE_LINE: &str = "Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H80000000,0,0,0,0,100,100,0,0,1,2,1,2,10,10,20,1";

/// Parse an ASS/SSA file into `SubtitleSegment`s. Timing lives in the
/// canonical `SubtitleSegment` fields; text ends up in
/// `translated_text` (imports typically bring translated subs into an
/// existing project).
pub fn parse(input: &str, start_id: u32) -> Result<Vec<SubtitleSegment>, String> {
    let normalised = input.replace("\r\n", "\n").replace('\r', "\n");
    let mut in_events = false;
    let mut format_fields: Vec<String> = Vec::new();
    let mut out = Vec::new();
    let mut next_id = start_id;

    for raw_line in normalised.lines() {
        let line = raw_line.trim_start_matches('\u{feff}');
        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }
        if let Some(section) = trimmed.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
            in_events = section.eq_ignore_ascii_case("Events");
            format_fields.clear();
            continue;
        }
        if !in_events {
            continue;
        }
        if let Some(rest) = strip_prefix_ci(trimmed, "Format:") {
            format_fields = rest
                .split(',')
                .map(|s| s.trim().to_ascii_lowercase())
                .collect();
            continue;
        }
        let Some(rest) = strip_prefix_ci(trimmed, "Dialogue:") else {
            continue;
        };
        if format_fields.is_empty() {
            // If the file omits an explicit Format line, assume the
            // canonical ordering from the ASS spec.
            format_fields = [
                "layer", "start", "end", "style", "name", "marginl", "marginr", "marginv",
                "effect", "text",
            ]
            .iter()
            .map(|s| s.to_string())
            .collect();
        }
        // Text is always the last field, and per spec it can contain
        // commas — so we split on the first N-1 commas only.
        let non_text_count = format_fields
            .iter()
            .filter(|f| f.as_str() != "text")
            .count();
        let values: Vec<&str> = rest.splitn(non_text_count + 1, ',').collect();
        if values.len() < format_fields.len() {
            continue;
        }
        let get = |field: &str| -> Option<&str> {
            format_fields
                .iter()
                .position(|f| f == field)
                .and_then(|i| values.get(i).map(|s| s.trim()))
        };
        let start = get("start")
            .ok_or_else(|| "Dialogue: missing Start field".to_string())
            .and_then(parse_ass_time)?;
        let end = get("end")
            .ok_or_else(|| "Dialogue: missing End field".to_string())
            .and_then(parse_ass_time)?;
        let text_raw = get("text").unwrap_or("");
        let text = clean_ass_text(text_raw);
        let speaker = get("name")
            .map(str::trim)
            .filter(|s| !s.is_empty())
            .map(String::from);

        let id = next_id;
        next_id = next_id.saturating_add(1);
        out.push(SubtitleSegment {
            id,
            start,
            end,
            source_text: String::new(),
            translated_text: text,
            dubbing_text: String::new(),
            words: None,
            speaker,
            voice_id: None,
        });
    }
    Ok(out)
}

/// Serialise `segments` to an ASS document string.
///
/// `text_for(seg)` picks which text field to render (translated /
/// source / bilingual — the caller decides).
pub fn write<'a, F>(
    segments: &'a [SubtitleSegment],
    source_language: &str,
    target_language: &str,
    text_for: F,
) -> String
where
    F: Fn(&'a SubtitleSegment) -> String,
{
    let mut out = String::new();
    out.push_str("[Script Info]\n");
    out.push_str("; Generated by Local Movie Translator\n");
    out.push_str(&format!("Title: {source_language} -> {target_language}\n"));
    out.push_str("ScriptType: v4.00+\n");
    out.push_str("Collisions: Normal\n");
    out.push_str("PlayResX: 1920\n");
    out.push_str("PlayResY: 1080\n");
    out.push_str("Timer: 100.0000\n");
    out.push_str("WrapStyle: 0\n\n");

    out.push_str("[V4+ Styles]\n");
    out.push_str("Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n");
    out.push_str(DEFAULT_STYLE_LINE);
    out.push_str("\n\n");

    out.push_str("[Events]\n");
    out.push_str(
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n",
    );
    for seg in segments {
        let start = format_ass_time(seg.start.max(0.0));
        let end = format_ass_time(seg.end.max(seg.start + 0.001));
        let text = escape_ass_text(&text_for(seg));
        let name = seg.speaker.as_deref().unwrap_or("");
        out.push_str(&format!(
            "Dialogue: 0,{start},{end},{style},{name},0,0,0,,{text}\n",
            style = DEFAULT_STYLE_NAME,
        ));
    }
    out
}

fn strip_prefix_ci<'a>(input: &'a str, prefix: &str) -> Option<&'a str> {
    if input.len() < prefix.len() {
        return None;
    }
    if input[..prefix.len()].eq_ignore_ascii_case(prefix) {
        Some(&input[prefix.len()..])
    } else {
        None
    }
}

fn parse_ass_time(s: &str) -> Result<f64, String> {
    // ASS uses `H:MM:SS.cs` (centiseconds). Sometimes seen as .ms.
    let trimmed = s.trim();
    let parts: Vec<&str> = trimmed.split(':').collect();
    let (h, m, tail) = match parts.as_slice() {
        [h, m, t] => (
            h.parse::<u32>().map_err(|_| format!("bad hours: {h}"))?,
            m.parse::<u32>().map_err(|_| format!("bad minutes: {m}"))?,
            *t,
        ),
        _ => return Err(format!("expected H:M:S.cs, got `{trimmed}`")),
    };
    let sec = tail
        .parse::<f64>()
        .map_err(|_| format!("bad seconds: {tail}"))?;
    Ok(h as f64 * 3600.0 + m as f64 * 60.0 + sec)
}

pub fn format_ass_time(t: f64) -> String {
    let total_cs = (t.max(0.0) * 100.0).round() as u64;
    let cs = total_cs % 100;
    let total_s = total_cs / 100;
    let s = total_s % 60;
    let total_m = total_s / 60;
    let m = total_m % 60;
    let h = total_m / 60;
    // ASS wants single-digit hours + zero-padded rest.
    format!("{h}:{m:02}:{s:02}.{cs:02}")
}

fn clean_ass_text(input: &str) -> String {
    // Strip `{...}` override groups, translate `\N` / `\n` / `\h` to
    // visible characters. Everything else passes through.
    let mut out = String::with_capacity(input.len());
    let mut chars = input.chars().peekable();
    while let Some(c) = chars.next() {
        match c {
            '{' => {
                // Skip until matching `}`.
                for skip in chars.by_ref() {
                    if skip == '}' {
                        break;
                    }
                }
            }
            '\\' => match chars.peek().copied() {
                Some('N') | Some('n') => {
                    out.push('\n');
                    chars.next();
                }
                Some('h') => {
                    out.push(' ');
                    chars.next();
                }
                _ => out.push(c),
            },
            _ => out.push(c),
        }
    }
    out
}

fn escape_ass_text(input: &str) -> String {
    // Only two things are unsafe in ASS Dialogue text: literal
    // newlines (they end the line) and literal braces (they open an
    // override group). Everything else — including commas — is fine.
    let mut out = String::with_capacity(input.len());
    for ch in input.chars() {
        match ch {
            '\n' => out.push_str("\\N"),
            '\r' => {}
            '{' => out.push_str("\\{"),
            '}' => out.push_str("\\}"),
            _ => out.push(ch),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_dialogue_lines() {
        let input = "[Script Info]\nTitle: t\n\n[V4+ Styles]\nFormat: Name\nStyle: Default\n\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\nDialogue: 0,0:00:01.00,0:00:02.50,Default,Alice,0,0,0,,{\\i1}Hello{\\i0}\\NWorld\n";
        let segs = parse(input, 0).unwrap();
        assert_eq!(segs.len(), 1);
        assert!((segs[0].start - 1.0).abs() < 1e-6);
        assert!((segs[0].end - 2.5).abs() < 1e-6);
        assert_eq!(segs[0].translated_text, "Hello\nWorld");
        assert_eq!(segs[0].speaker.as_deref(), Some("Alice"));
    }

    #[test]
    fn writes_and_reparses_roundtrip() {
        let seg = SubtitleSegment {
            id: 3,
            start: 4.32,
            end: 6.15,
            source_text: String::new(),
            translated_text: "Xin chào, thế giới!".into(),
            dubbing_text: String::new(),
            words: None,
            speaker: Some("Bob".into()),
            voice_id: None,
        };
        let ass = write(std::slice::from_ref(&seg), "en", "vi", |s| {
            s.translated_text.clone()
        });
        let parsed = parse(&ass, 0).unwrap();
        assert_eq!(parsed.len(), 1);
        assert!((parsed[0].start - 4.32).abs() < 0.02);
        assert!((parsed[0].end - 6.15).abs() < 0.02);
        assert_eq!(parsed[0].translated_text, "Xin chào, thế giới!");
        assert_eq!(parsed[0].speaker.as_deref(), Some("Bob"));
    }

    #[test]
    fn text_with_commas_survives() {
        let seg = SubtitleSegment {
            id: 1,
            start: 0.0,
            end: 1.0,
            source_text: String::new(),
            translated_text: "one, two, three".into(),
            dubbing_text: String::new(),
            words: None,
            speaker: None,
            voice_id: None,
        };
        let ass = write(std::slice::from_ref(&seg), "en", "vi", |s| {
            s.translated_text.clone()
        });
        let parsed = parse(&ass, 0).unwrap();
        assert_eq!(parsed[0].translated_text, "one, two, three");
    }
}
